"""
src/services/report_service.py

LLM-backed SEO audit report generation service.

Responsibility: take the structured audit evidence produced by
extractor_service and the guidance context loaded by prompt_loader,
call the configured LLM provider via llm_service.generate_text(), and
return a completed Markdown SEO audit report.

The report_service is the only module that calls the LLM (through the
shared llm_service dispatcher). All other services are deterministic.
Keeping LLM usage isolated here makes it easy to audit token usage,
swap models, and mock the API in tests.

Hallucination prevention
------------------------
The evidence package passed to the LLM is the only factual input.
The system prompt explicitly instructs the LLM to use only verified
evidence and to write ``Could not be verified in this audit.`` for
every field that was not measurable from static content.

Public interface
----------------
    generate_report(
        normalized_url,
        evidence,
        prompt_context,
        settings,
    ) -> ReportResult
"""

import logging  # Standard logging — records every LLM call attempt, success, and failure
import re  # re.finditer extracts PART headings from the template at runtime
import time  # time.perf_counter measures elapsed audit execution time
import uuid  # uuid.uuid4 generates a unique ID for each audit
from dataclasses import dataclass  # dataclass defines the structured result returned to the caller
from datetime import datetime, timezone  # datetime.now(timezone.utc) for timezone-aware UTC timestamps

from src.config import Settings  # Settings provides the API key and model configuration
from src.services.extractor_service import (
    AuditEvidence,      # Structured verified SEO data extracted from the website
    RobotsTxtEvidence,  # Robots.txt findings — used in evidence formatting
    SitemapEvidence,    # Sitemap accessibility data — used in evidence formatting
)
from src.services.llm_service import calculate_cost_usd, generate_text  # Provider-neutral dispatcher (Gemini/Perplexity/OpenAI)
from src.services.prompt_loader import PromptContext  # Loaded guidance files context

# Module-level logger
logger = logging.getLogger(__name__)  # Resolves to "src.services.report_service"


def _extract_required_part_headings(master_report_structure: str) -> tuple[str, ...]:
    """
    Derive required PART/SECTION headings from the live template content.

    Reads the headings that are actually present in MASTER_REPORT_STRUCTURE.md
    so the validator always reflects the current template, regardless of how
    many parts/sections the file contains.
    """
    return tuple(
        m.group(0)
        for m in re.finditer(r"^# (?:PART|SECTION) \d+:", master_report_structure, re.MULTILINE)
    )


# Phrases that must never leak into a client-facing report — see the
# "Originality & Source Integrity" rules in seo_audit.prompt.md.
#
# NOTE: "perplexity"/"chatgpt"/"gemini" are NOT banned as bare words — SECTION 5.2
# (AI Search / GEO Visibility) legitimately discusses these platforms as SEO
# targets. Only self-attribution phrasing (the model naming itself as the
# report's author/tool) is contamination and gets flagged.
_BANNED_PHRASES: tuple[str, ...] = (
    "comet browser",
    "google docs",
    "convert to google docs",
    "generated by perplexity",
    "generated using perplexity",
    "generated with perplexity",
    "created by perplexity",
    "as perplexity",
    "i am perplexity",
    "generated by chatgpt",
    "generated using chatgpt",
    "generated with chatgpt",
    "created by chatgpt",
    "as chatgpt",
    "i am chatgpt",
    "generated by gemini",
    "generated using gemini",
    "generated with gemini",
    "created by gemini",
    "as an ai language model",
)


def _find_banned_phrases(markdown_report: str) -> list[str]:
    """
    Return any contamination/branding phrases found in the generated report.

    Guards against AI-tool branding, prior chat transcripts, or workflow
    instructions leaking into the client-facing report.
    """
    lowered: str = markdown_report.lower()
    return [phrase for phrase in _BANNED_PHRASES if phrase in lowered]


def _extract_section_body(markdown_report: str, heading_prefix: str) -> str | None:
    """
    Return the text following a heading line starting with heading_prefix,
    up to the next Markdown heading (any level), or None if not found.

    Used to inspect the content of a specific subsection (e.g. "## 7.2")
    without depending on its exact trailing wording.
    """
    pattern = re.compile(
        rf"^{re.escape(heading_prefix)}[^\n]*\n([\s\S]*?)(?=^#{{1,6}} |\Z)",
        re.MULTILINE,
    )
    match = pattern.search(markdown_report)
    return match.group(1).strip() if match else None


def _validate_location_section(markdown_report: str) -> list[str]:
    """
    Enforce SECTION 3's conditional rule: exactly one of 3.2 or 3.3 must be
    completed, with the other explicitly marked not applicable.

    Returns a list of human-readable issue descriptions (empty if the
    section is well-formed or SECTION 3 is absent from this template).
    """
    section_32: str | None = _extract_section_body(markdown_report, "## 3.2")
    section_33: str | None = _extract_section_body(markdown_report, "## 3.3")

    if section_32 is None or section_33 is None:
        # Missing headings are already reported by the required-heading check.
        return []

    is_32_not_applicable: bool = "not applicable" in section_32.lower()
    is_33_not_applicable: bool = "not applicable" in section_33.lower()

    if is_32_not_applicable and is_33_not_applicable:
        return ["SECTION 3 sections 3.2 and 3.3 are both marked not applicable — exactly one must be completed"]
    if not is_32_not_applicable and not is_33_not_applicable:
        return ["SECTION 3 sections 3.2 and 3.3 are both completed — exactly one must be marked not applicable"]
    return []


def _find_table_blocks(markdown_report: str) -> list[list[str]]:
    """
    Return each Markdown table in the report as a list of its pipe-delimited
    lines (header row, separator row, and all data rows).
    """
    tables: list[list[str]] = []
    current: list[str] = []

    for line in markdown_report.splitlines():
        stripped = line.strip()
        if stripped.startswith("|") and stripped.endswith("|"):
            current.append(stripped)
        else:
            if len(current) >= 2:
                tables.append(current)
            current = []
    if len(current) >= 2:
        tables.append(current)

    return tables


def _split_table_row(row: str) -> list[str]:
    """Split a Markdown table row into trimmed cell values, dropping the outer pipes."""
    return [cell.strip() for cell in row.strip().strip("|").split("|")]


def _validate_citation_columns(markdown_report: str) -> list[str]:
    """
    Flag data rows in Source/Retrieved-cited tables (PARTS 5-7) that omit a citation.

    Any table whose header includes both a "Source" and "Retrieved" column
    must not contain a data row with an empty value in either column — see
    the External Research Citation Rules in seo_audit.prompt.md.
    """
    issues: list[str] = []

    for table in _find_table_blocks(markdown_report):
        header_cells: list[str] = [cell.lower() for cell in _split_table_row(table[0])]
        if "source" not in header_cells or "retrieved" not in header_cells:
            continue

        source_index: int = header_cells.index("source")
        retrieved_index: int = header_cells.index("retrieved")

        # table[1] is the "---|---" separator row; data rows start at index 2.
        for row_number, data_row in enumerate(table[2:], start=1):
            cells: list[str] = _split_table_row(data_row)
            if len(cells) <= max(source_index, retrieved_index):
                continue  # malformed row width — not this validator's concern

            if not cells[source_index] or not cells[retrieved_index]:
                issues.append(
                    f"Row {row_number} of a Source/Retrieved table is missing a citation value"
                )

    return issues


# ---------------------------------------------------------------------------
# Result data model
# ---------------------------------------------------------------------------

@dataclass
class ReportResult:
    """
    The completed SEO audit report.

    Returned by generate_report() and consumed by the API route, which
    stores it in the reports/ folder and returns it to the UI.
    """

    audit_id: str
    # Unique identifier for this audit — used as the filename

    normalized_url: str
    # The URL that was audited — included in the report for reference

    markdown_report: str
    # The full Markdown-formatted SEO audit report generated by the LLM

    created_at: datetime
    # UTC timestamp when the report generation completed

    elapsed_seconds: float = 0.0
    # Total elapsed execution time for report generation in seconds

    input_tokens: int = 0
    # Total prompt/context tokens consumed by the LLM

    output_tokens: int = 0
    # Total completion tokens generated by the LLM

    estimated_cost_usd: float = 0.0
    # Estimated cost in USD incurred across all LLM requests for this audit


# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------

async def generate_report(
    normalized_url: str,
    evidence: AuditEvidence,
    prompt_context: PromptContext,
    settings: Settings,
    audit_id: str | None = None,
) -> ReportResult:
    """
    Generate a Markdown SEO audit report using the configured LLM provider.

    Workflow:
      1. Format the verified evidence as a structured text block.
      2. Substitute the website URL into the audit prompt template.
      3. Build the LLM request (system prompt + user message).
      4. Call the configured provider asynchronously (non-blocking) via generate_text().
      5. Return the report with a unique audit ID and timestamp.

    Args:
        normalized_url: The website URL that was audited.
        evidence: Verified SEO data from extractor_service.extract().
        prompt_context: Loaded guidance files from prompt_loader.load_prompt_context().
        settings: Application settings providing the LLM provider, API key, and model name.
        audit_id: Pre-generated ID to reuse (e.g. from an already-created
            job record); a new one is generated if not supplied.

    Returns:
        ReportResult containing the Markdown report, audit ID, and metadata.

    Raises:
        ValueError: If the configured provider's API key is not set (raised by generate_text()).
        LLMProviderError: If the LLM fails to return a usable response.
    """
    start_time: float = time.perf_counter()
    logger.info("Starting report generation for: %s", normalized_url)

    total_input_tokens: int = 0
    total_output_tokens: int = 0
    total_cost_usd: float = 0.0

    # --- Step 1: Format the audit evidence as structured text ---------------

    evidence_text: str = _format_evidence(normalized_url, evidence)
    # Converts the AuditEvidence dataclass into a readable Markdown-formatted block
    # This is the "user message" that tells the LLM what was found on the website

    # --- Step 2: Substitute URL into the audit prompt -----------------------

    audit_prompt_with_url: str = prompt_context.audit_prompt.replace(
        "{{website_url}}",  # The template placeholder defined in seo_audit.prompt.md
        normalized_url,      # The actual URL being audited
    )
    # The audit prompt now contains the real URL where the placeholder was

    # Build the updated PromptContext with the URL-substituted audit prompt
    # This preserves the other guidance files unchanged
    context_with_url = PromptContext(
        audit_prompt=audit_prompt_with_url,
        seo_skill=prompt_context.seo_skill,
        master_report_structure=prompt_context.master_report_structure,
        ai_guidelines=prompt_context.ai_guidelines,
    )

    # --- Step 3: Build LLM request ------------------------------------------

    system_prompt: str = context_with_url.combined_system_prompt
    # The combined system prompt includes all four guidance files assembled in priority order:
    # AI guidelines → SEO methodology → Report spec → Audit prompt (with real URL)

    user_message: str = _build_user_message(
        normalized_url=normalized_url,
        evidence_text=evidence_text,
        master_report_structure=prompt_context.master_report_structure,
    )
    # The user message presents the verified evidence and asks for the report

    logger.debug(
        "LLM request prepared: system=%d chars, user=%d chars",
        len(system_prompt),
        len(user_message),
    )

    # --- Step 4: Call the configured LLM provider --------------------------

    markdown_report: str = await generate_text(system_prompt, user_message, settings)
    usage = getattr(markdown_report, "usage", None)
    if usage is not None:
        total_input_tokens += usage.input_tokens
        total_output_tokens += usage.output_tokens
        total_cost_usd += usage.estimated_cost_usd
    else:
        in_tok = max(1, len(system_prompt + user_message) // 4)
        out_tok = max(1, len(str(markdown_report)) // 4)
        model_name = getattr(settings, f"{settings.llm_provider}_model", "")
        cost = calculate_cost_usd(settings.llm_provider, model_name, in_tok, out_tok)
        total_input_tokens += in_tok
        total_output_tokens += out_tok
        total_cost_usd += cost

    # Derive required headings from the template that was actually used for this run.
    # This reflects any parts the user has added or removed from MASTER_REPORT_STRUCTURE.md.
    required_headings: tuple[str, ...] = _extract_required_part_headings(
        prompt_context.master_report_structure
    )

    # Log structural drift if the model omits required report parts.
    # This keeps the request successful while making inconsistency observable.
    missing_parts: list[str] = _missing_required_report_parts(markdown_report, required_headings)
    if missing_parts:
        logger.warning(
            "Generated report for %s is missing required sections: %s",
            normalized_url,
            ", ".join(missing_parts),
        )

    # Detect provider branding/chat-transcript contamination (see Originality &
    # Source Integrity rules). This is checked alongside missing-part drift so
    # a single retry can address both issues in one extra call.
    banned_phrases: list[str] = _find_banned_phrases(markdown_report)
    if banned_phrases:
        logger.warning(
            "Generated report for %s contains banned contamination phrases: %s",
            normalized_url,
            ", ".join(banned_phrases),
        )

    # Validate SECTION 3's conditional location/market-expansion rule.
    location_issues: list[str] = _validate_location_section(markdown_report)
    if location_issues:
        logger.warning(
            "Generated report for %s has SECTION 3 conditional issues: %s",
            normalized_url,
            "; ".join(location_issues),
        )

    # Validate that every Source/Retrieved-cited table (SECTION 1-3) has no
    # rows with an empty citation column.
    citation_issues: list[str] = _validate_citation_columns(markdown_report)
    if citation_issues:
        logger.warning(
            "Generated report for %s has citation issues: %s",
            normalized_url,
            "; ".join(citation_issues),
        )

    if missing_parts or banned_phrases or location_issues or citation_issues:
        # One retry only when the model produced a partially structured report.
        # If all required headings are missing, a retry often repeats the same failure.
        all_headings_missing: bool = bool(missing_parts) and len(missing_parts) == len(required_headings)
        if not all_headings_missing:
            retry_user_message: str = _build_retry_user_message(
                user_message, missing_parts, banned_phrases, location_issues, citation_issues
            )
            markdown_report = await generate_text(system_prompt, retry_user_message, settings)
            retry_usage = getattr(markdown_report, "usage", None)
            if retry_usage is not None:
                total_input_tokens += retry_usage.input_tokens
                total_output_tokens += retry_usage.output_tokens
                total_cost_usd += retry_usage.estimated_cost_usd
            else:
                in_tok = max(1, len(system_prompt + retry_user_message) // 4)
                out_tok = max(1, len(str(markdown_report)) // 4)
                model_name = getattr(settings, f"{settings.llm_provider}_model", "")
                cost = calculate_cost_usd(settings.llm_provider, model_name, in_tok, out_tok)
                total_input_tokens += in_tok
                total_output_tokens += out_tok
                total_cost_usd += cost

            missing_parts = _missing_required_report_parts(markdown_report, required_headings)
            banned_phrases = _find_banned_phrases(markdown_report)
            location_issues = _validate_location_section(markdown_report)
            citation_issues = _validate_citation_columns(markdown_report)
            if missing_parts:
                logger.warning(
                    "Retry report for %s is still missing required sections: %s",
                    normalized_url,
                    ", ".join(missing_parts),
                )
            if banned_phrases:
                logger.warning(
                    "Retry report for %s still contains banned contamination phrases: %s",
                    normalized_url,
                    ", ".join(banned_phrases),
                )
            if location_issues:
                logger.warning(
                    "Retry report for %s still has SECTION 3 conditional issues: %s",
                    normalized_url,
                    "; ".join(location_issues),
                )
            if citation_issues:
                logger.warning(
                    "Retry report for %s still has citation issues: %s",
                    normalized_url,
                    "; ".join(citation_issues),
                )
            if not missing_parts and not banned_phrases and not location_issues and not citation_issues:
                logger.info(
                    "Retry report for %s now includes all required PART sections with no contamination",
                    normalized_url,
                )
        else:
            logger.warning(
                "Retry skipped for %s because all required PART headings were missing in first response",
                normalized_url,
            )

    # --- Step 6: Assemble and return the result ----------------------------

    resolved_audit_id: str = audit_id or str(uuid.uuid4())
    # Only generate a fresh ID if the caller didn't already supply one

    created_at: datetime = datetime.now(timezone.utc)
    # Record the UTC completion time using a timezone-aware datetime (avoids DeprecationWarning)
    elapsed_seconds: float = round(time.perf_counter() - start_time, 2)

    logger.info(
        "Report generated for %s: audit_id=%s, length=%d chars, elapsed=%.2fs, in_tok=%d, out_tok=%d, cost=$%.4f",
        normalized_url,
        resolved_audit_id,
        len(markdown_report),
        elapsed_seconds,
        total_input_tokens,
        total_output_tokens,
        total_cost_usd,
    )

    return ReportResult(
        audit_id=resolved_audit_id,
        normalized_url=normalized_url,
        markdown_report=str(markdown_report),
        created_at=created_at,
        elapsed_seconds=elapsed_seconds,
        input_tokens=total_input_tokens,
        output_tokens=total_output_tokens,
        estimated_cost_usd=round(total_cost_usd, 6),
    )


# ---------------------------------------------------------------------------
# Evidence formatting helpers
# ---------------------------------------------------------------------------

def _format_evidence(normalized_url: str, evidence: AuditEvidence) -> str:
    """
    Convert an AuditEvidence dataclass into a structured Markdown text block.

    This text is passed to the LLM as the factual input for the report.
    The LLM must use only this data — it must not invent additional findings.

    Args:
        normalized_url: The URL that was audited.
        evidence: The structured evidence from extractor_service.

    Returns:
        A Markdown-formatted string describing all verified findings.
    """
    lines: list[str] = []  # Accumulate text lines before joining

    lines.append(f"## Verified Audit Evidence for {normalized_url}")
    lines.append("")  # Blank line for readability

    # --- Homepage status ----------------------------------------------------

    lines.append("### Homepage")
    lines.append(f"- Final URL: {evidence.final_url or normalized_url}")
    lines.append(f"- HTTP Status: {evidence.http_status}")
    lines.append(f"- HTTPS: {'Yes' if evidence.is_https else 'No'}")
    lines.append("")

    # --- Page metadata -------------------------------------------------------

    lines.append("### Page Metadata")

    if evidence.page_title:
        lines.append(f"- Title: \"{evidence.page_title}\"")
        lines.append(f"- Title Length: {evidence.page_title_length} characters")
    else:
        lines.append("- Title: **Missing** — no <title> element found")
        lines.append("- Title Length: 0 characters")

    if evidence.meta_description:
        lines.append(f"- Meta Description: \"{evidence.meta_description}\"")
        lines.append(f"- Meta Description Length: {evidence.meta_description_length} characters")
    else:
        lines.append("- Meta Description: **Missing** — no <meta name=\"description\"> element found")
        lines.append("- Meta Description Length: 0 characters")

    if evidence.canonical_url:
        lines.append(f"- Canonical URL: {evidence.canonical_url}")
    else:
        lines.append("- Canonical URL: Not found in static HTML")

    if evidence.page_language:
        lines.append(f"- Page Language: {evidence.page_language}")
    else:
        lines.append("- Page Language: Not declared on <html> element")

    lines.append("")

    # --- Heading structure --------------------------------------------------

    lines.append("### Heading Structure")
    lines.append(f"- H1 Tags Found: {len(evidence.h1_tags)}")

    if evidence.h1_tags:
        for h1 in evidence.h1_tags:
            lines.append(f"  - \"{h1}\"")
    else:
        lines.append("  - **No H1 tags found**")

    lines.append(f"- H2 Tags Found: {len(evidence.h2_tags)}")

    if evidence.h2_tags[:5]:
        # Show only the first 5 H2s to keep the prompt concise
        for h2 in evidence.h2_tags[:5]:
            lines.append(f"  - \"{h2}\"")
        if len(evidence.h2_tags) > 5:
            lines.append(f"  - ... and {len(evidence.h2_tags) - 5} more H2 tags")

    lines.append("")

    # --- Links ---------------------------------------------------------------

    lines.append("### Links")
    lines.append(f"- Internal Links: {len(evidence.internal_links)} unique URLs found")
    lines.append(f"- External Links: {len(evidence.external_links)} unique URLs found")
    lines.append("")

    # --- Images --------------------------------------------------------------

    lines.append("### Images")
    lines.append(f"- Total Images: {len(evidence.images)}")
    lines.append(f"- Images Missing ALT Attribute: {evidence.images_missing_alt_count}")
    lines.append(f"- Images With Empty ALT (alt=\"\"): {evidence.images_empty_alt_count}")
    lines.append("")

    # --- robots.txt ----------------------------------------------------------

    lines.append("### robots.txt")

    if evidence.robots_txt is None:
        lines.append("- robots.txt: Not fetched")
    elif not evidence.robots_txt.is_accessible:
        lines.append(f"- robots.txt: Not accessible (HTTP {evidence.robots_txt.http_status})")
        lines.append("- Disallow Rules: Could not be verified in this audit.")
    else:
        lines.append(f"- robots.txt: Accessible (HTTP {evidence.robots_txt.http_status})")
        lines.append(f"- Blocks Root Path (/): {'**Yes — all robots blocked**' if evidence.robots_txt.blocks_root_path else 'No'}")

        if evidence.robots_txt.disallow_rules:
            lines.append(f"- Disallow Rules ({len(evidence.robots_txt.disallow_rules)} found):")
            for rule in evidence.robots_txt.disallow_rules[:10]:
                # Limit to 10 rules to keep the prompt a reasonable length
                lines.append(f"  - Disallow: {rule}")
            if len(evidence.robots_txt.disallow_rules) > 10:
                lines.append(f"  - ... and {len(evidence.robots_txt.disallow_rules) - 10} more rules")
        else:
            lines.append("- Disallow Rules: None (all paths accessible to robots)")

        if evidence.robots_txt.sitemap_urls:
            lines.append(f"- Sitemap URLs in robots.txt ({len(evidence.robots_txt.sitemap_urls)}):")
            for url in evidence.robots_txt.sitemap_urls:
                lines.append(f"  - {url}")
        else:
            lines.append("- Sitemap URLs in robots.txt: None declared")

    lines.append("")

    # --- Sitemaps ------------------------------------------------------------

    lines.append("### Sitemaps")

    if not evidence.sitemaps:
        lines.append("- No sitemaps were fetched.")
    else:
        for sitemap in evidence.sitemaps:
            status_text = (
                f"Accessible (HTTP {sitemap.http_status}, {sitemap.url_count} URLs)"
                if sitemap.is_accessible
                else f"Not accessible (HTTP {sitemap.http_status})"
            )
            lines.append(f"- {sitemap.url}: {status_text}")
            # Include discovered URLs so the LLM can populate page-inventory tables
            for u in sitemap.urls:
                lines.append(f"  - {u}")

    lines.append("")

    # --- Unverifiable fields -------------------------------------------------

    lines.append("### Technical Metrics That Could Not Be Verified")
    lines.append(
        "The following specific technical metrics CANNOT be measured from static content. "
        "For each metric listed below ONLY, write: \"Could not be verified in this audit.\" "
        "Do NOT use this phrase in SEO Notes, Slug-Based Topic, Current Status, or any "
        "recommendation column — those must always contain URL-based SEO strategy."
    )
    lines.append("")

    for field_name in evidence.unverifiable_fields:
        lines.append(f"- {field_name}")

    return "\n".join(lines)
    # Join all lines into a single string for the LLM user message


def _build_user_message(
    normalized_url: str,
    evidence_text: str,
    master_report_structure: str | None = None,
) -> str:
    """
    Build the user-turn message for the LLM conversation.

    The user message combines the task instruction and the evidence.
    Keeping the task instruction here (rather than only in the system prompt)
    reinforces the request in case the system instruction is truncated.

    Args:
        normalized_url: The website URL being audited.
        evidence_text: The formatted evidence text from _format_evidence().
        master_report_structure: Optional full report template text that must
                                 be reproduced verbatim by the LLM.

    Returns:
        A complete user message string ready to send to the LLM.
    """
    if master_report_structure:
        return (
            f"Generate the SEO audit report for: {normalized_url}\n\n"
            "## MANDATORY OUTPUT RULES\n"
            "- Reproduce the provided template exactly in the same order.\n"
            "- Keep all headings, sub-headings, and table column names unchanged.\n"
            "- Do not add, remove, rename, or reorder sections.\n"
            "- Fill every section/table cell using verified evidence and URL-based analysis.\n"
            "- Do not write paragraphs anywhere. If a section lacks a table, format all content strictly as concise bullet points with minimum words.\n"
            "- Never write 'Not Detected' or 'Could not be verified in this audit.' in any table cell.\n"
            "- Do not output any extra wrapper text before or after the report.\n\n"
            "## TEMPLATE TO FILL (VERBATIM STRUCTURE)\n\n"
            f"{master_report_structure}\n\n"
            "---\n\n"
            "## VERIFIED EVIDENCE\n\n"
            f"{evidence_text}"
        )

    return (
        f"Please generate a complete, professional SEO audit report for: {normalized_url}\n\n"
        f"Use only the verified evidence below. "
        f"Do not invent any findings that are not supported by the evidence. "
        f"For every field listed under 'Fields That Could Not Be Verified', "
        f"write exactly: \"Could not be verified in this audit.\"\n\n"
        f"{evidence_text}"
    )


def _missing_required_report_parts(
    markdown_report: str,
    required_headings: tuple[str, ...],
) -> list[str]:
    """
    Return required PART headings that are missing from the generated report.

    Args:
        markdown_report: The LLM-generated Markdown text to validate.
        required_headings: PART headings extracted from the active template.

    This is a lightweight validation helper for observability only.
    """
    return [
        heading
        for heading in required_headings
        if heading not in markdown_report
    ]


def _build_retry_user_message(
    original_user_message: str,
    missing_parts: list[str],
    banned_phrases: list[str] | None = None,
    location_issues: list[str] | None = None,
    citation_issues: list[str] | None = None,
) -> str:
    """
    Build a second-pass instruction that fixes missing headings, contamination,
    SECTION 3 conditional-section violations, and/or missing citations.

    Args:
        original_user_message: The original report-generation user message.
        missing_parts: Required PART headings not found in the first output.
        banned_phrases: Contamination/branding phrases found in the first output.
        location_issues: SECTION 3 conditional-section rule violations, if any.
        citation_issues: Source/Retrieved citation-column violations, if any.

    Returns:
        A reinforced user message for one additional LLM attempt.
    """
    instruction_blocks: list[str] = []

    if missing_parts:
        missing_text: str = "\n".join(f"- {heading}" for heading in missing_parts)
        instruction_blocks.append(
            "Your previous output was missing required report parts.\n"
            "Regenerate the full report using the exact same template structure.\n"
            "Do not omit any required PART heading.\n"
            "The following headings were missing and must be present exactly:\n"
            f"{missing_text}"
        )

    if banned_phrases:
        banned_text: str = "\n".join(f"- {phrase}" for phrase in banned_phrases)
        instruction_blocks.append(
            "Your previous output contained forbidden branding or contamination text.\n"
            "Regenerate the full report and do not include any of the following phrases, "
            "or similar references, anywhere in the output:\n"
            f"{banned_text}"
        )

    if location_issues:
        location_text: str = "\n".join(f"- {issue}" for issue in location_issues)
        instruction_blocks.append(
            "Your previous output violated the SECTION 3 conditional-section rule.\n"
            "Exactly one of section 3.2 (Local Location Opportunities) or 3.3 "
            "(Audience & Market Expansion Opportunities) must be completed, and the "
            "other must state it is not applicable.\n"
            f"{location_text}"
        )

    if citation_issues:
        citation_text: str = "\n".join(f"- {issue}" for issue in citation_issues)
        instruction_blocks.append(
            "Your previous output had table rows missing a Source or Retrieved value.\n"
            "Every row in a table with Source/Retrieved columns must cite where the "
            "estimate came from and the audit retrieval date — never leave either cell blank.\n"
            f"{citation_text}"
        )

    instructions: str = "\n\n".join(instruction_blocks)

    return (
        f"{original_user_message}\n\n"
        "## RETRY INSTRUCTION (MANDATORY)\n"
        f"{instructions}\n"
    )
