"""
src/services/report_service.py

LLM-backed SEO audit report generation service.

Responsibility: take the structured audit evidence produced by
extractor_service and the guidance context loaded by prompt_loader,
call the Gemini LLM, and return a completed Markdown SEO audit report.

The report_service is the only module that calls the LLM.  All other
services are deterministic.  Keeping LLM usage isolated here makes it
easy to audit token usage, swap models, and mock the API in tests.

Hallucination prevention
------------------------
The evidence package passed to the LLM is the only factual input.
The system prompt explicitly instructs Gemini to use only verified
evidence and to write ``Could not be verified in this audit.`` for
every field that was not measurable from static content.

Public interface
----------------
    generate_report(
        normalized_url,
        evidence,
        prompt_context,
        settings,
    ) -> ReportResult
"""

import asyncio  # asyncio.to_thread runs the synchronous Gemini SDK call in a thread pool
import logging  # Standard logging — records every LLM call attempt, success, and failure
import os  # os.makedirs creates the reports/ output directory if it does not exist
import uuid  # uuid.uuid4 generates a unique ID for each audit
from dataclasses import dataclass  # dataclass defines the structured result returned to the caller
from datetime import datetime, timezone  # datetime.now(timezone.utc) for timezone-aware UTC timestamps
from pathlib import Path  # Path handles OS-agnostic file paths for report storage

import google.generativeai as genai  # Google Gemini SDK — the LLM used for report generation

from src.config import Settings  # Settings provides the API key and model configuration
from src.services.extractor_service import (
    AuditEvidence,      # Structured verified SEO data extracted from the website
    RobotsTxtEvidence,  # Robots.txt findings — used in evidence formatting
    SitemapEvidence,    # Sitemap accessibility data — used in evidence formatting
)
from src.services.prompt_loader import PromptContext  # Loaded guidance files context

# Module-level logger
logger = logging.getLogger(__name__)  # Resolves to "src.services.report_service"

# Minimum structure guardrails for the final markdown output.
# We log missing parts for observability but do not fail the audit request.
_REQUIRED_REPORT_PART_HEADINGS: tuple[str, ...] = (
    "# PART 1:",
    "# PART 2:",
    "# PART 3:",
    "# PART 4:",
    "# PART 5:",
    "# PART 6:",
    "# PART 7:",
    "# PART 8:",
)


# ---------------------------------------------------------------------------
# Result data model
# ---------------------------------------------------------------------------

@dataclass
class ReportResult:
    """
    The completed SEO audit report.

    Returned by generate_report() and consumed by the API route, which
    stores it in the reports/ folder and returns it to the UI.
    """

    audit_id: str
    # Unique identifier for this audit — used as the filename and PDF download key

    normalized_url: str
    # The URL that was audited — included in the report for reference

    markdown_report: str
    # The full Markdown-formatted SEO audit report generated by the LLM

    created_at: datetime
    # UTC timestamp when the report generation completed


# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------

async def generate_report(
    normalized_url: str,
    evidence: AuditEvidence,
    prompt_context: PromptContext,
    settings: Settings,
) -> ReportResult:
    """
    Generate a Markdown SEO audit report using the Gemini LLM.

    Workflow:
      1. Validate the API key is configured.
      2. Format the verified evidence as a structured text block.
      3. Substitute the website URL into the audit prompt template.
      4. Build the LLM request (system prompt + user message).
      5. Call Gemini asynchronously (non-blocking).
      6. Return the report with a unique audit ID and timestamp.

    Args:
        normalized_url: The website URL that was audited.
        evidence: Verified SEO data from extractor_service.extract().
        prompt_context: Loaded guidance files from prompt_loader.load_prompt_context().
        settings: Application settings providing the Gemini API key and model name.

    Returns:
        ReportResult containing the Markdown report, audit ID, and metadata.

    Raises:
        ValueError: If the Gemini API key is not configured.
        RuntimeError: If the LLM fails to return a usable response.
    """
    logger.info("Starting report generation for: %s", normalized_url)

    # --- Step 1: Validate API key -------------------------------------------

    if not settings.gemini_api_key:
        # Fail fast with a clear message rather than crashing inside the Gemini SDK
        raise ValueError(
            "GEMINI_API_KEY is not configured. "
            "Add it to the .env file: GEMINI_API_KEY=your_key_here"
        )

    # --- Step 2: Format the audit evidence as structured text ---------------

    evidence_text: str = _format_evidence(normalized_url, evidence)
    # Converts the AuditEvidence dataclass into a readable Markdown-formatted block
    # This is the "user message" that tells the LLM what was found on the website

    # --- Step 3: Substitute URL into the audit prompt -----------------------

    audit_prompt_with_url: str = prompt_context.audit_prompt.replace(
        "{{website_url}}",  # The template placeholder defined in seo_audit.prompt.md
        normalized_url,      # The actual URL being audited
    )
    # The audit prompt now contains the real URL where the placeholder was

    # Build the updated PromptContext with the URL-substituted audit prompt
    # This preserves the other guidance files unchanged
    context_with_url = PromptContext(
        audit_prompt=audit_prompt_with_url,
        seo_skill=prompt_context.seo_skill,
        master_report_structure=prompt_context.master_report_structure,
        ai_guidelines=prompt_context.ai_guidelines,
    )

    # --- Step 4: Build LLM request ------------------------------------------

    system_prompt: str = context_with_url.combined_system_prompt
    # The combined system prompt includes all four guidance files assembled in priority order:
    # AI guidelines → SEO methodology → Report spec → Audit prompt (with real URL)

    user_message: str = _build_user_message(
        normalized_url=normalized_url,
        evidence_text=evidence_text,
        master_report_structure=prompt_context.master_report_structure,
    )
    # The user message presents the verified evidence and asks for the report

    logger.debug(
        "LLM request prepared: system=%d chars, user=%d chars",
        len(system_prompt),
        len(user_message),
    )

    # --- Step 5: Call Gemini ------------------------------------------------

    markdown_report: str = await _call_gemini(
        system_prompt=system_prompt,
        user_message=user_message,
        settings=settings,
    )

    # Log structural drift if the model omits required report parts.
    # This keeps the request successful while making inconsistency observable.
    missing_parts: list[str] = _missing_required_report_parts(markdown_report)
    if missing_parts:
        logger.warning(
            "Generated report for %s is missing required sections: %s",
            normalized_url,
            ", ".join(missing_parts),
        )

        # One retry only when the model produced a partially structured report.
        # If all required headings are missing, a retry often repeats the same failure.
        if len(missing_parts) < len(_REQUIRED_REPORT_PART_HEADINGS):
            retry_user_message: str = _build_retry_user_message(user_message, missing_parts)
            markdown_report = await _call_gemini(
                system_prompt=system_prompt,
                user_message=retry_user_message,
                settings=settings,
            )

            missing_parts = _missing_required_report_parts(markdown_report)
            if missing_parts:
                logger.warning(
                    "Retry report for %s is still missing required sections: %s",
                    normalized_url,
                    ", ".join(missing_parts),
                )
            else:
                logger.info("Retry report for %s now includes all required PART sections", normalized_url)
        else:
            logger.warning(
                "Retry skipped for %s because all required PART headings were missing in first response",
                normalized_url,
            )

    # --- Step 6: Assemble and return the result ----------------------------

    audit_id: str = str(uuid.uuid4())
    # Generate a unique ID for this audit — used as the filename and download key

    created_at: datetime = datetime.now(timezone.utc)
    # Record the UTC completion time using a timezone-aware datetime (avoids DeprecationWarning)

    logger.info(
        "Report generated for %s: audit_id=%s, length=%d chars",
        normalized_url,
        audit_id,
        len(markdown_report),
    )

    return ReportResult(
        audit_id=audit_id,
        normalized_url=normalized_url,
        markdown_report=markdown_report,
        created_at=created_at,
    )


# ---------------------------------------------------------------------------
# LLM call helper
# ---------------------------------------------------------------------------

async def _call_gemini(
    system_prompt: str,
    user_message: str,
    settings: Settings,
) -> str:
    """
    Configure and call the Gemini API asynchronously.

    The Gemini SDK's generate_content() is synchronous.  We run it in a
    thread-pool executor via asyncio.to_thread() so it does not block the
    FastAPI event loop while waiting for the LLM response.

    Args:
        system_prompt: Combined guidance context sent as the system instruction.
        user_message: Formatted audit evidence sent as the user turn.
        settings: Provides GEMINI_API_KEY and GEMINI_MODEL.

    Returns:
        The Markdown text content from the LLM response.

    Raises:
        RuntimeError: If the LLM returns an empty or blocked response.
    """
    logger.info("Calling Gemini model: %s", settings.gemini_model)

    genai.configure(api_key=settings.gemini_api_key)
    # Configure the SDK with the API key from .env — done here (not at module import)
    # so tests can mock genai before any configuration takes place

    model = genai.GenerativeModel(
        model_name=settings.gemini_model,          # "gemini-1.5-flash" by default
        system_instruction=system_prompt,           # All four guidance files as the system context
    )
    # GenerativeModel holds the system instruction — it is not part of the conversation history

    try:
        # Run the synchronous SDK call in a thread pool to avoid blocking the event loop
        response = await asyncio.to_thread(
            model.generate_content,   # The synchronous SDK function to call
            user_message,              # The formatted evidence as the user turn
        )
        # asyncio.to_thread wraps a synchronous function as an awaitable coroutine

    except Exception as llm_error:
        # Catch any SDK-level exception (network error, quota exceeded, invalid key, etc.)
        logger.error("Gemini API call failed: %s", llm_error)
        raise RuntimeError(
            f"LLM report generation failed: {llm_error}. "
            "Check GEMINI_API_KEY in .env and verify the API is reachable."
        ) from llm_error

    # Validate the response contains usable text
    if not response or not response.text:
        logger.error("Gemini returned an empty or blocked response")
        raise RuntimeError(
            "The LLM returned an empty response. "
            "This may occur if the request was blocked by safety filters. "
            "Try with a different URL or check the Gemini safety settings."
        )

    logger.info("Gemini response received: %d characters", len(response.text))

    return response.text  # The Markdown report text


# ---------------------------------------------------------------------------
# Evidence formatting helpers
# ---------------------------------------------------------------------------

def _format_evidence(normalized_url: str, evidence: AuditEvidence) -> str:
    """
    Convert an AuditEvidence dataclass into a structured Markdown text block.

    This text is passed to the LLM as the factual input for the report.
    The LLM must use only this data — it must not invent additional findings.

    Args:
        normalized_url: The URL that was audited.
        evidence: The structured evidence from extractor_service.

    Returns:
        A Markdown-formatted string describing all verified findings.
    """
    lines: list[str] = []  # Accumulate text lines before joining

    lines.append(f"## Verified Audit Evidence for {normalized_url}")
    lines.append("")  # Blank line for readability

    # --- Homepage status ----------------------------------------------------

    lines.append("### Homepage")
    lines.append(f"- Final URL: {evidence.final_url or normalized_url}")
    lines.append(f"- HTTP Status: {evidence.http_status}")
    lines.append(f"- HTTPS: {'Yes' if evidence.is_https else 'No'}")
    lines.append("")

    # --- Page metadata -------------------------------------------------------

    lines.append("### Page Metadata")

    if evidence.page_title:
        lines.append(f"- Title: \"{evidence.page_title}\"")
        lines.append(f"- Title Length: {evidence.page_title_length} characters")
    else:
        lines.append("- Title: **Missing** — no <title> element found")
        lines.append("- Title Length: 0 characters")

    if evidence.meta_description:
        lines.append(f"- Meta Description: \"{evidence.meta_description}\"")
        lines.append(f"- Meta Description Length: {evidence.meta_description_length} characters")
    else:
        lines.append("- Meta Description: **Missing** — no <meta name=\"description\"> element found")
        lines.append("- Meta Description Length: 0 characters")

    if evidence.canonical_url:
        lines.append(f"- Canonical URL: {evidence.canonical_url}")
    else:
        lines.append("- Canonical URL: Not found in static HTML")

    if evidence.page_language:
        lines.append(f"- Page Language: {evidence.page_language}")
    else:
        lines.append("- Page Language: Not declared on <html> element")

    lines.append("")

    # --- Heading structure --------------------------------------------------

    lines.append("### Heading Structure")
    lines.append(f"- H1 Tags Found: {len(evidence.h1_tags)}")

    if evidence.h1_tags:
        for h1 in evidence.h1_tags:
            lines.append(f"  - \"{h1}\"")
    else:
        lines.append("  - **No H1 tags found**")

    lines.append(f"- H2 Tags Found: {len(evidence.h2_tags)}")

    if evidence.h2_tags[:5]:
        # Show only the first 5 H2s to keep the prompt concise
        for h2 in evidence.h2_tags[:5]:
            lines.append(f"  - \"{h2}\"")
        if len(evidence.h2_tags) > 5:
            lines.append(f"  - ... and {len(evidence.h2_tags) - 5} more H2 tags")

    lines.append("")

    # --- Links ---------------------------------------------------------------

    lines.append("### Links")
    lines.append(f"- Internal Links: {len(evidence.internal_links)} unique URLs found")
    lines.append(f"- External Links: {len(evidence.external_links)} unique URLs found")
    lines.append("")

    # --- Images --------------------------------------------------------------

    lines.append("### Images")
    lines.append(f"- Total Images: {len(evidence.images)}")
    lines.append(f"- Images Missing ALT Attribute: {evidence.images_missing_alt_count}")
    lines.append(f"- Images With Empty ALT (alt=\"\"): {evidence.images_empty_alt_count}")
    lines.append("")

    # --- robots.txt ----------------------------------------------------------

    lines.append("### robots.txt")

    if evidence.robots_txt is None:
        lines.append("- robots.txt: Not fetched")
    elif not evidence.robots_txt.is_accessible:
        lines.append(f"- robots.txt: Not accessible (HTTP {evidence.robots_txt.http_status})")
        lines.append("- Disallow Rules: Could not be verified in this audit.")
    else:
        lines.append(f"- robots.txt: Accessible (HTTP {evidence.robots_txt.http_status})")
        lines.append(f"- Blocks Root Path (/): {'**Yes — all robots blocked**' if evidence.robots_txt.blocks_root_path else 'No'}")

        if evidence.robots_txt.disallow_rules:
            lines.append(f"- Disallow Rules ({len(evidence.robots_txt.disallow_rules)} found):")
            for rule in evidence.robots_txt.disallow_rules[:10]:
                # Limit to 10 rules to keep the prompt a reasonable length
                lines.append(f"  - Disallow: {rule}")
            if len(evidence.robots_txt.disallow_rules) > 10:
                lines.append(f"  - ... and {len(evidence.robots_txt.disallow_rules) - 10} more rules")
        else:
            lines.append("- Disallow Rules: None (all paths accessible to robots)")

        if evidence.robots_txt.sitemap_urls:
            lines.append(f"- Sitemap URLs in robots.txt ({len(evidence.robots_txt.sitemap_urls)}):")
            for url in evidence.robots_txt.sitemap_urls:
                lines.append(f"  - {url}")
        else:
            lines.append("- Sitemap URLs in robots.txt: None declared")

    lines.append("")

    # --- Sitemaps ------------------------------------------------------------

    lines.append("### Sitemaps")

    if not evidence.sitemaps:
        lines.append("- No sitemaps were fetched.")
    else:
        for sitemap in evidence.sitemaps:
            status_text = (
                f"Accessible (HTTP {sitemap.http_status}, {sitemap.url_count} URLs)"
                if sitemap.is_accessible
                else f"Not accessible (HTTP {sitemap.http_status})"
            )
            lines.append(f"- {sitemap.url}: {status_text}")

    lines.append("")

    # --- Unverifiable fields -------------------------------------------------

    lines.append("### Fields That Could Not Be Verified")
    lines.append(
        "The following items CANNOT be determined from static content. "
        "For each, write: \"Could not be verified in this audit.\""
    )
    lines.append("")

    for field_name in evidence.unverifiable_fields:
        lines.append(f"- {field_name}")

    return "\n".join(lines)
    # Join all lines into a single string for the LLM user message


def _build_user_message(
    normalized_url: str,
    evidence_text: str,
    master_report_structure: str | None = None,
) -> str:
    """
    Build the user-turn message for the Gemini conversation.

    The user message combines the task instruction and the evidence.
    Keeping the task instruction here (rather than only in the system prompt)
    reinforces the request in case the system instruction is truncated.

    Args:
        normalized_url: The website URL being audited.
        evidence_text: The formatted evidence text from _format_evidence().
        master_report_structure: Optional full report template text that must
                                 be reproduced verbatim by the LLM.

    Returns:
        A complete user message string ready to send to the LLM.
    """
    if master_report_structure:
        return (
            f"Generate the SEO audit report for: {normalized_url}\n\n"
            "## MANDATORY OUTPUT RULES\n"
            "- Reproduce the provided template exactly in the same order.\n"
            "- Keep all headings, sub-headings, and table column names unchanged.\n"
            "- Do not add, remove, rename, or reorder sections.\n"
            "- Fill every section/table cell using verified evidence only.\n"
            "- If evidence is unavailable, write either 'Not Detected' or 'Could not be verified in this audit.'\n"
            "- Do not output any extra wrapper text before or after the report.\n\n"
            "## TEMPLATE TO FILL (VERBATIM STRUCTURE)\n\n"
            f"{master_report_structure}\n\n"
            "---\n\n"
            "## VERIFIED EVIDENCE\n\n"
            f"{evidence_text}"
        )

    return (
        f"Please generate a complete, professional SEO audit report for: {normalized_url}\n\n"
        f"Use only the verified evidence below. "
        f"Do not invent any findings that are not supported by the evidence. "
        f"For every field listed under 'Fields That Could Not Be Verified', "
        f"write exactly: \"Could not be verified in this audit.\"\n\n"
        f"{evidence_text}"
    )


def _missing_required_report_parts(markdown_report: str) -> list[str]:
    """
    Return required PART headings that are missing from the generated report.

    This is a lightweight validation helper for observability only.
    """
    return [
        heading
        for heading in _REQUIRED_REPORT_PART_HEADINGS
        if heading not in markdown_report
    ]


def _build_retry_user_message(original_user_message: str, missing_parts: list[str]) -> str:
    """
    Build a second-pass instruction that explicitly demands missing headings.

    Args:
        original_user_message: The original report-generation user message.
        missing_parts: Required PART headings not found in the first output.

    Returns:
        A reinforced user message for one additional LLM attempt.
    """
    missing_text: str = "\n".join(f"- {heading}" for heading in missing_parts)

    return (
        f"{original_user_message}\n\n"
        "## RETRY INSTRUCTION (MANDATORY)\n"
        "Your previous output was missing required report parts.\n"
        "Regenerate the full report using the exact same template structure.\n"
        "Do not omit any required PART heading.\n"
        "The following headings were missing and must be present exactly:\n"
        f"{missing_text}\n"
    )
